ALTER TABLE app_users
  ADD COLUMN age INTEGER NOT NULL DEFAULT 18 CHECK (age BETWEEN 13 AND 120),
  ADD COLUMN gender VARCHAR(24) NOT NULL DEFAULT 'prefer_not_to_say',
  ADD COLUMN phone VARCHAR(32) NOT NULL DEFAULT 'unknown';