ALTER TABLE print_orders
  ADD COLUMN IF NOT EXISTS document_id UUID REFERENCES documents(id),
  ADD COLUMN IF NOT EXISTS paper_type VARCHAR(32) NOT NULL DEFAULT 'PLAIN',
  ADD COLUMN IF NOT EXISTS duplex BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS orientation VARCHAR(16) NOT NULL DEFAULT 'PORTRAIT';

CREATE INDEX IF NOT EXISTS idx_print_orders_document ON print_orders(document_id);